from __future__ import annotations

# Base padrão carregada quando data/dados_copa.json não existe.
# Mantém 104 partidas: fase de grupos + mata-mata com placeholders.
DEFAULT_MATCHES = [{'id': 'm001',
  'numero': 1,
  'data': '2026-06-11',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo A',
  'time_a': 'México',
  'sigla_a': 'MEX',
  'pais_a': 'MX',
  'time_b': 'África do Sul',
  'sigla_b': 'RSA',
  'pais_b': 'ZA',
  'estadio': 'Mexico City Stadium',
  'cidade': 'Cidade do México',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'encerrado',
  'placar_a': 2,
  'placar_b': 0,
  'placar': '2-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm002',
  'numero': 2,
  'data': '2026-06-11',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo A',
  'time_a': 'Coreia do Sul',
  'sigla_a': 'KOR',
  'pais_a': 'KR',
  'time_b': 'Tchéquia',
  'sigla_b': 'CZE',
  'pais_b': 'CZ',
  'estadio': 'Guadalajara Stadium',
  'cidade': 'Zapopan',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'encerrado',
  'placar_a': 2,
  'placar_b': 1,
  'placar': '2-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm003',
  'numero': 3,
  'data': '2026-06-12',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo B',
  'time_a': 'Canadá',
  'sigla_a': 'CAN',
  'pais_a': 'CA',
  'time_b': 'Bósnia e Herzegovina',
  'sigla_b': 'BIH',
  'pais_b': 'BA',
  'estadio': 'Toronto Stadium',
  'cidade': 'Toronto',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm004',
  'numero': 4,
  'data': '2026-06-12',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo D',
  'time_a': 'Estados Unidos',
  'sigla_a': 'USA',
  'pais_a': 'US',
  'time_b': 'Paraguai',
  'sigla_b': 'PAR',
  'pais_b': 'PY',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 4,
  'placar_b': 1,
  'placar': '4-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm005',
  'numero': 5,
  'data': '2026-06-13',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo C',
  'time_a': 'Haiti',
  'sigla_a': 'HAI',
  'pais_a': 'HT',
  'time_b': 'Escócia',
  'sigla_b': 'SCO',
  'pais_b': 'GB-SCT',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 0,
  'placar_b': 1,
  'placar': '0-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm006',
  'numero': 6,
  'data': '2026-06-14',
  'hora': '01:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo D',
  'time_a': 'Austrália',
  'sigla_a': 'AUS',
  'pais_a': 'AU',
  'time_b': 'Turquia',
  'sigla_b': 'TUR',
  'pais_b': 'TR',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'encerrado',
  'placar_a': 2,
  'placar_b': 0,
  'placar': '2-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm007',
  'numero': 7,
  'data': '2026-06-13',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo C',
  'time_a': 'Brasil',
  'sigla_a': 'BRA',
  'pais_a': 'BR',
  'time_b': 'Marrocos',
  'sigla_b': 'MAR',
  'pais_b': 'MA',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm008',
  'numero': 8,
  'data': '2026-06-13',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo B',
  'time_a': 'Catar',
  'sigla_a': 'QAT',
  'pais_a': 'QA',
  'time_b': 'Suíça',
  'sigla_b': 'SUI',
  'pais_b': 'CH',
  'estadio': 'San Francisco Bay Area Stadium',
  'cidade': 'Santa Clara',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm009',
  'numero': 9,
  'data': '2026-06-14',
  'hora': '20:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo E',
  'time_a': 'Costa do Marfim',
  'sigla_a': 'CIV',
  'pais_a': 'CI',
  'time_b': 'Equador',
  'sigla_b': 'ECU',
  'pais_b': 'EC',
  'estadio': 'Philadelphia Stadium',
  'cidade': 'Filadélfia',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 0,
  'placar': '1-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm010',
  'numero': 10,
  'data': '2026-06-14',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo E',
  'time_a': 'Alemanha',
  'sigla_a': 'GER',
  'pais_a': 'DE',
  'time_b': 'Curaçao',
  'sigla_b': 'CUW',
  'pais_b': 'CW',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 7,
  'placar_b': 1,
  'placar': '7-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm011',
  'numero': 11,
  'data': '2026-06-14',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo F',
  'time_a': 'Países Baixos',
  'sigla_a': 'NED',
  'pais_a': 'NL',
  'time_b': 'Japão',
  'sigla_b': 'JPN',
  'pais_b': 'JP',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 2,
  'placar_b': 2,
  'placar': '2-2',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm012',
  'numero': 12,
  'data': '2026-06-14',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo F',
  'time_a': 'Suécia',
  'sigla_a': 'SWE',
  'pais_a': 'SE',
  'time_b': 'Tunísia',
  'sigla_b': 'TUN',
  'pais_b': 'TN',
  'estadio': 'Monterrey Stadium',
  'cidade': 'Monterrey',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'encerrado',
  'placar_a': 5,
  'placar_b': 1,
  'placar': '5-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm013',
  'numero': 13,
  'data': '2026-06-15',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo H',
  'time_a': 'Arábia Saudita',
  'sigla_a': 'KSA',
  'pais_a': 'SA',
  'time_b': 'Uruguai',
  'sigla_b': 'URU',
  'pais_b': 'UY',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm014',
  'numero': 14,
  'data': '2026-06-15',
  'hora': '13:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo H',
  'time_a': 'Espanha',
  'sigla_a': 'ESP',
  'pais_a': 'ES',
  'time_b': 'Cabo Verde',
  'sigla_b': 'CPV',
  'pais_b': 'CV',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 0,
  'placar_b': 0,
  'placar': '0-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm015',
  'numero': 15,
  'data': '2026-06-15',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo G',
  'time_a': 'Irã',
  'sigla_a': 'IRN',
  'pais_a': 'IR',
  'time_b': 'Nova Zelândia',
  'sigla_b': 'NZL',
  'pais_b': 'NZ',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 2,
  'placar_b': 2,
  'placar': '2-2',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm016',
  'numero': 16,
  'data': '2026-06-15',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo G',
  'time_a': 'Bélgica',
  'sigla_a': 'BEL',
  'pais_a': 'BE',
  'time_b': 'Egito',
  'sigla_b': 'EGY',
  'pais_b': 'EG',
  'estadio': 'Seattle Stadium',
  'cidade': 'Seattle',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm017',
  'numero': 17,
  'data': '2026-06-16',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo I',
  'time_a': 'França',
  'sigla_a': 'FRA',
  'pais_a': 'FR',
  'time_b': 'Senegal',
  'sigla_b': 'SEN',
  'pais_b': 'SN',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 3,
  'placar_b': 1,
  'placar': '3-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm018',
  'numero': 18,
  'data': '2026-06-16',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo I',
  'time_a': 'Iraque',
  'sigla_a': 'IRQ',
  'pais_a': 'IQ',
  'time_b': 'Noruega',
  'sigla_b': 'NOR',
  'pais_b': 'NO',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 4,
  'placar': '1-4',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm019',
  'numero': 19,
  'data': '2026-06-16',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo J',
  'time_a': 'Argentina',
  'sigla_a': 'ARG',
  'pais_a': 'AR',
  'time_b': 'Argélia',
  'sigla_b': 'ALG',
  'pais_b': 'DZ',
  'estadio': 'Kansas City Stadium',
  'cidade': 'Kansas City',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 3,
  'placar_b': 0,
  'placar': '3-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm020',
  'numero': 20,
  'data': '2026-06-17',
  'hora': '01:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo J',
  'time_a': 'Áustria',
  'sigla_a': 'AUT',
  'pais_a': 'AT',
  'time_b': 'Jordânia',
  'sigla_b': 'JOR',
  'pais_b': 'JO',
  'estadio': 'San Francisco Bay Area Stadium',
  'cidade': 'Santa Clara',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 3,
  'placar_b': 1,
  'placar': '3-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm021',
  'numero': 21,
  'data': '2026-06-17',
  'hora': '20:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo L',
  'time_a': 'Gana',
  'sigla_a': 'GHA',
  'pais_a': 'GH',
  'time_b': 'Panamá',
  'sigla_b': 'PAN',
  'pais_b': 'PA',
  'estadio': 'Toronto Stadium',
  'cidade': 'Toronto',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 0,
  'placar': '1-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm022',
  'numero': 22,
  'data': '2026-06-17',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo L',
  'time_a': 'Inglaterra',
  'sigla_a': 'ENG',
  'pais_a': 'GB-ENG',
  'time_b': 'Croácia',
  'sigla_b': 'CRO',
  'pais_b': 'HR',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 4,
  'placar_b': 2,
  'placar': '4-2',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm023',
  'numero': 23,
  'data': '2026-06-17',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo K',
  'time_a': 'Portugal',
  'sigla_a': 'POR',
  'pais_a': 'PT',
  'time_b': 'RD Congo',
  'sigla_b': 'COD',
  'pais_b': 'CD',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm024',
  'numero': 24,
  'data': '2026-06-17',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo K',
  'time_a': 'Uzbequistão',
  'sigla_a': 'UZB',
  'pais_a': 'UZ',
  'time_b': 'Colômbia',
  'sigla_b': 'COL',
  'pais_b': 'CO',
  'estadio': 'Mexico City Stadium',
  'cidade': 'Cidade do México',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 3,
  'placar': '1-3',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm025',
  'numero': 25,
  'data': '2026-06-18',
  'hora': '13:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo A',
  'time_a': 'Tchéquia',
  'sigla_a': 'CZE',
  'pais_a': 'CZ',
  'time_b': 'África do Sul',
  'sigla_b': 'RSA',
  'pais_b': 'ZA',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 1,
  'placar': '1-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm026',
  'numero': 26,
  'data': '2026-06-18',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo B',
  'time_a': 'Suíça',
  'sigla_a': 'SUI',
  'pais_a': 'CH',
  'time_b': 'Bósnia e Herzegovina',
  'sigla_b': 'BIH',
  'pais_b': 'BA',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 4,
  'placar_b': 1,
  'placar': '4-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm027',
  'numero': 27,
  'data': '2026-06-18',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo B',
  'time_a': 'Canadá',
  'sigla_a': 'CAN',
  'pais_a': 'CA',
  'time_b': 'Catar',
  'sigla_b': 'QAT',
  'pais_b': 'QA',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'encerrado',
  'placar_a': 6,
  'placar_b': 0,
  'placar': '6-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm028',
  'numero': 28,
  'data': '2026-06-18',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo A',
  'time_a': 'México',
  'sigla_a': 'MEX',
  'pais_a': 'MX',
  'time_b': 'Coreia do Sul',
  'sigla_b': 'KOR',
  'pais_b': 'KR',
  'estadio': 'Guadalajara Stadium',
  'cidade': 'Zapopan',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'encerrado',
  'placar_a': 1,
  'placar_b': 0,
  'placar': '1-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm029',
  'numero': 29,
  'data': '2026-06-19',
  'hora': '21:30',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo C',
  'time_a': 'Brasil',
  'sigla_a': 'BRA',
  'pais_a': 'BR',
  'time_b': 'Haiti',
  'sigla_b': 'HAI',
  'pais_b': 'HT',
  'estadio': 'Philadelphia Stadium',
  'cidade': 'Filadélfia',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 3,
  'placar_b': 0,
  'placar': '3-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm030',
  'numero': 30,
  'data': '2026-06-19',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo C',
  'time_a': 'Escócia',
  'sigla_a': 'SCO',
  'pais_a': 'GB-SCT',
  'time_b': 'Marrocos',
  'sigla_b': 'MAR',
  'pais_b': 'MA',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 0,
  'placar_b': 1,
  'placar': '0-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm031',
  'numero': 31,
  'data': '2026-06-20',
  'hora': '00:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo D',
  'time_a': 'Turquia',
  'sigla_a': 'TUR',
  'pais_a': 'TR',
  'time_b': 'Paraguai',
  'sigla_b': 'PAR',
  'pais_b': 'PY',
  'estadio': 'San Francisco Bay Area Stadium',
  'cidade': 'Santa Clara',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 0,
  'placar_b': 1,
  'placar': '0-1',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm032',
  'numero': 32,
  'data': '2026-06-19',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo D',
  'time_a': 'Estados Unidos',
  'sigla_a': 'USA',
  'pais_a': 'US',
  'time_b': 'Austrália',
  'sigla_b': 'AUS',
  'pais_b': 'AU',
  'estadio': 'Seattle Stadium',
  'cidade': 'Seattle',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'encerrado',
  'placar_a': 2,
  'placar_b': 0,
  'placar': '2-0',
  'alerta': False,
  'favorito': False,
  'destaque': 'Resultado importado do cronograma atual.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm033',
  'numero': 33,
  'data': '2026-06-20',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo E',
  'time_a': 'Alemanha',
  'sigla_a': 'GER',
  'pais_a': 'DE',
  'time_b': 'Costa do Marfim',
  'sigla_b': 'CIV',
  'pais_b': 'CI',
  'estadio': 'Toronto Stadium',
  'cidade': 'Toronto',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm034',
  'numero': 34,
  'data': '2026-06-20',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo E',
  'time_a': 'Equador',
  'sigla_a': 'ECU',
  'pais_a': 'EC',
  'time_b': 'Curaçao',
  'sigla_b': 'CUW',
  'pais_b': 'CW',
  'estadio': 'Kansas City Stadium',
  'cidade': 'Kansas City',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm035',
  'numero': 35,
  'data': '2026-06-20',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo F',
  'time_a': 'Países Baixos',
  'sigla_a': 'NED',
  'pais_a': 'NL',
  'time_b': 'Suécia',
  'sigla_b': 'SWE',
  'pais_b': 'SE',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm036',
  'numero': 36,
  'data': '2026-06-21',
  'hora': '01:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo F',
  'time_a': 'Tunísia',
  'sigla_a': 'TUN',
  'pais_a': 'TN',
  'time_b': 'Japão',
  'sigla_b': 'JPN',
  'pais_b': 'JP',
  'estadio': 'Monterrey Stadium',
  'cidade': 'Monterrey',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm037',
  'numero': 37,
  'data': '2026-06-21',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo H',
  'time_a': 'Uruguai',
  'sigla_a': 'URU',
  'pais_a': 'UY',
  'time_b': 'Cabo Verde',
  'sigla_b': 'CPV',
  'pais_b': 'CV',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm038',
  'numero': 38,
  'data': '2026-06-21',
  'hora': '13:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo H',
  'time_a': 'Espanha',
  'sigla_a': 'ESP',
  'pais_a': 'ES',
  'time_b': 'Arábia Saudita',
  'sigla_b': 'KSA',
  'pais_b': 'SA',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm039',
  'numero': 39,
  'data': '2026-06-21',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo G',
  'time_a': 'Bélgica',
  'sigla_a': 'BEL',
  'pais_a': 'BE',
  'time_b': 'Irã',
  'sigla_b': 'IRN',
  'pais_b': 'IR',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm040',
  'numero': 40,
  'data': '2026-06-21',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo G',
  'time_a': 'Nova Zelândia',
  'sigla_a': 'NZL',
  'pais_a': 'NZ',
  'time_b': 'Egito',
  'sigla_b': 'EGY',
  'pais_b': 'EG',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm041',
  'numero': 41,
  'data': '2026-06-22',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo I',
  'time_a': 'Noruega',
  'sigla_a': 'NOR',
  'pais_a': 'NO',
  'time_b': 'Senegal',
  'sigla_b': 'SEN',
  'pais_b': 'SN',
  'estadio': 'Toronto Stadium',
  'cidade': 'Toronto',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm042',
  'numero': 42,
  'data': '2026-06-22',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo I',
  'time_a': 'França',
  'sigla_a': 'FRA',
  'pais_a': 'FR',
  'time_b': 'Iraque',
  'sigla_b': 'IRQ',
  'pais_b': 'IQ',
  'estadio': 'Philadelphia Stadium',
  'cidade': 'Filadélfia',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm043',
  'numero': 43,
  'data': '2026-06-22',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo J',
  'time_a': 'Argentina',
  'sigla_a': 'ARG',
  'pais_a': 'AR',
  'time_b': 'Áustria',
  'sigla_b': 'AUT',
  'pais_b': 'AT',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm044',
  'numero': 44,
  'data': '2026-06-23',
  'hora': '00:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo J',
  'time_a': 'Jordânia',
  'sigla_a': 'JOR',
  'pais_a': 'JO',
  'time_b': 'Argélia',
  'sigla_b': 'ALG',
  'pais_b': 'DZ',
  'estadio': 'San Francisco Bay Area Stadium',
  'cidade': 'Santa Clara',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm045',
  'numero': 45,
  'data': '2026-06-23',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo L',
  'time_a': 'Inglaterra',
  'sigla_a': 'ENG',
  'pais_a': 'GB-ENG',
  'time_b': 'Gana',
  'sigla_b': 'GHA',
  'pais_b': 'GH',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm046',
  'numero': 46,
  'data': '2026-06-23',
  'hora': '20:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo L',
  'time_a': 'Panamá',
  'sigla_a': 'PAN',
  'pais_a': 'PA',
  'time_b': 'Croácia',
  'sigla_b': 'CRO',
  'pais_b': 'HR',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm047',
  'numero': 47,
  'data': '2026-06-23',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo K',
  'time_a': 'Portugal',
  'sigla_a': 'POR',
  'pais_a': 'PT',
  'time_b': 'Uzbequistão',
  'sigla_b': 'UZB',
  'pais_b': 'UZ',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm048',
  'numero': 48,
  'data': '2026-06-23',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo K',
  'time_a': 'Colômbia',
  'sigla_a': 'COL',
  'pais_a': 'CO',
  'time_b': 'RD Congo',
  'sigla_b': 'COD',
  'pais_b': 'CD',
  'estadio': 'Guadalajara Stadium',
  'cidade': 'Zapopan',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm049',
  'numero': 49,
  'data': '2026-06-24',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo C',
  'time_a': 'Escócia',
  'sigla_a': 'SCO',
  'pais_a': 'GB-SCT',
  'time_b': 'Brasil',
  'sigla_b': 'BRA',
  'pais_b': 'BR',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm050',
  'numero': 50,
  'data': '2026-06-24',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo C',
  'time_a': 'Marrocos',
  'sigla_a': 'MAR',
  'pais_a': 'MA',
  'time_b': 'Haiti',
  'sigla_b': 'HAI',
  'pais_b': 'HT',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm051',
  'numero': 51,
  'data': '2026-06-24',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo B',
  'time_a': 'Suíça',
  'sigla_a': 'SUI',
  'pais_a': 'CH',
  'time_b': 'Canadá',
  'sigla_b': 'CAN',
  'pais_b': 'CA',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm052',
  'numero': 52,
  'data': '2026-06-24',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo B',
  'time_a': 'Bósnia e Herzegovina',
  'sigla_a': 'BIH',
  'pais_a': 'BA',
  'time_b': 'Catar',
  'sigla_b': 'QAT',
  'pais_b': 'QA',
  'estadio': 'Seattle Stadium',
  'cidade': 'Seattle',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm053',
  'numero': 53,
  'data': '2026-06-24',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo A',
  'time_a': 'Tchéquia',
  'sigla_a': 'CZE',
  'pais_a': 'CZ',
  'time_b': 'México',
  'sigla_b': 'MEX',
  'pais_b': 'MX',
  'estadio': 'Mexico City Stadium',
  'cidade': 'Cidade do México',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm054',
  'numero': 54,
  'data': '2026-06-24',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo A',
  'time_a': 'África do Sul',
  'sigla_a': 'RSA',
  'pais_a': 'ZA',
  'time_b': 'Coreia do Sul',
  'sigla_b': 'KOR',
  'pais_b': 'KR',
  'estadio': 'Monterrey Stadium',
  'cidade': 'Monterrey',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm055',
  'numero': 55,
  'data': '2026-06-25',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo E',
  'time_a': 'Curaçao',
  'sigla_a': 'CUW',
  'pais_a': 'CW',
  'time_b': 'Costa do Marfim',
  'sigla_b': 'CIV',
  'pais_b': 'CI',
  'estadio': 'Philadelphia Stadium',
  'cidade': 'Filadélfia',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm056',
  'numero': 56,
  'data': '2026-06-25',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo E',
  'time_a': 'Equador',
  'sigla_a': 'ECU',
  'pais_a': 'EC',
  'time_b': 'Alemanha',
  'sigla_b': 'GER',
  'pais_b': 'DE',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm057',
  'numero': 57,
  'data': '2026-06-25',
  'hora': '20:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo F',
  'time_a': 'Japão',
  'sigla_a': 'JPN',
  'pais_a': 'JP',
  'time_b': 'Suécia',
  'sigla_b': 'SWE',
  'pais_b': 'SE',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm058',
  'numero': 58,
  'data': '2026-06-25',
  'hora': '20:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo F',
  'time_a': 'Tunísia',
  'sigla_a': 'TUN',
  'pais_a': 'TN',
  'time_b': 'Países Baixos',
  'sigla_b': 'NED',
  'pais_b': 'NL',
  'estadio': 'Kansas City Stadium',
  'cidade': 'Kansas City',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm059',
  'numero': 59,
  'data': '2026-06-25',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo D',
  'time_a': 'Turquia',
  'sigla_a': 'TUR',
  'pais_a': 'TR',
  'time_b': 'Estados Unidos',
  'sigla_b': 'USA',
  'pais_b': 'US',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm060',
  'numero': 60,
  'data': '2026-06-25',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo D',
  'time_a': 'Paraguai',
  'sigla_a': 'PAR',
  'pais_a': 'PY',
  'time_b': 'Austrália',
  'sigla_b': 'AUS',
  'pais_b': 'AU',
  'estadio': 'San Francisco Bay Area Stadium',
  'cidade': 'Santa Clara',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm061',
  'numero': 61,
  'data': '2026-06-26',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo I',
  'time_a': 'Noruega',
  'sigla_a': 'NOR',
  'pais_a': 'NO',
  'time_b': 'França',
  'sigla_b': 'FRA',
  'pais_b': 'FR',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm062',
  'numero': 62,
  'data': '2026-06-26',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo I',
  'time_a': 'Senegal',
  'sigla_a': 'SEN',
  'pais_a': 'SN',
  'time_b': 'Iraque',
  'sigla_b': 'IRQ',
  'pais_b': 'IQ',
  'estadio': 'Toronto Stadium',
  'cidade': 'Toronto',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm063',
  'numero': 63,
  'data': '2026-06-27',
  'hora': '00:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo G',
  'time_a': 'Egito',
  'sigla_a': 'EGY',
  'pais_a': 'EG',
  'time_b': 'Irã',
  'sigla_b': 'IRN',
  'pais_b': 'IR',
  'estadio': 'Seattle Stadium',
  'cidade': 'Seattle',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm064',
  'numero': 64,
  'data': '2026-06-27',
  'hora': '00:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo G',
  'time_a': 'Nova Zelândia',
  'sigla_a': 'NZL',
  'pais_a': 'NZ',
  'time_b': 'Bélgica',
  'sigla_b': 'BEL',
  'pais_b': 'BE',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm065',
  'numero': 65,
  'data': '2026-06-26',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo H',
  'time_a': 'Cabo Verde',
  'sigla_a': 'CPV',
  'pais_a': 'CV',
  'time_b': 'Arábia Saudita',
  'sigla_b': 'KSA',
  'pais_b': 'SA',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm066',
  'numero': 66,
  'data': '2026-06-26',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo H',
  'time_a': 'Uruguai',
  'sigla_a': 'URU',
  'pais_a': 'UY',
  'time_b': 'Espanha',
  'sigla_b': 'ESP',
  'pais_b': 'ES',
  'estadio': 'Guadalajara Stadium',
  'cidade': 'Zapopan',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm067',
  'numero': 67,
  'data': '2026-06-27',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo L',
  'time_a': 'Panamá',
  'sigla_a': 'PAN',
  'pais_a': 'PA',
  'time_b': 'Inglaterra',
  'sigla_b': 'ENG',
  'pais_b': 'GB-ENG',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm068',
  'numero': 68,
  'data': '2026-06-27',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo L',
  'time_a': 'Croácia',
  'sigla_a': 'CRO',
  'pais_a': 'HR',
  'time_b': 'Gana',
  'sigla_b': 'GHA',
  'pais_b': 'GH',
  'estadio': 'Philadelphia Stadium',
  'cidade': 'Filadélfia',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm069',
  'numero': 69,
  'data': '2026-06-27',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo J',
  'time_a': 'Argélia',
  'sigla_a': 'ALG',
  'pais_a': 'DZ',
  'time_b': 'Áustria',
  'sigla_b': 'AUT',
  'pais_b': 'AT',
  'estadio': 'Kansas City Stadium',
  'cidade': 'Kansas City',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm070',
  'numero': 70,
  'data': '2026-06-27',
  'hora': '23:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo J',
  'time_a': 'Jordânia',
  'sigla_a': 'JOR',
  'pais_a': 'JO',
  'time_b': 'Argentina',
  'sigla_b': 'ARG',
  'pais_b': 'AR',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm071',
  'numero': 71,
  'data': '2026-06-27',
  'hora': '20:30',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo K',
  'time_a': 'Colômbia',
  'sigla_a': 'COL',
  'pais_a': 'CO',
  'time_b': 'Portugal',
  'sigla_b': 'POR',
  'pais_b': 'PT',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm072',
  'numero': 72,
  'data': '2026-06-27',
  'hora': '20:30',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Fase de grupos',
  'grupo': 'Grupo K',
  'time_a': 'RD Congo',
  'sigla_a': 'COD',
  'pais_a': 'CD',
  'time_b': 'Uzbequistão',
  'sigla_b': 'UZB',
  'pais_b': 'UZ',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Partida programada no calendário da Copa 2026.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial'},
 {'id': 'm073',
  'numero': 73,
  'data': '2026-06-28',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '2º Grupo A',
  'sigla_a': '2ºG',
  'pais_a': '',
  'time_b': '2º Grupo B',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm074',
  'numero': 74,
  'data': '2026-06-29',
  'hora': '17:30',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo E',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo A/B/C/D/F',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm075',
  'numero': 75,
  'data': '2026-06-29',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo F',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '2º Grupo C',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Monterrey Stadium',
  'cidade': 'Monterrey',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm076',
  'numero': 76,
  'data': '2026-06-29',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo C',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '2º Grupo F',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm077',
  'numero': 77,
  'data': '2026-06-30',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo I',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo C/D/F/G/H',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm078',
  'numero': 78,
  'data': '2026-06-30',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '2º Grupo E',
  'sigla_a': '2ºG',
  'pais_a': '',
  'time_b': '2º Grupo I',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm079',
  'numero': 79,
  'data': '2026-06-30',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo A',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo C/E/F/H/I',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'Mexico City Stadium',
  'cidade': 'Cidade do México',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm080',
  'numero': 80,
  'data': '2026-07-01',
  'hora': '13:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo L',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo E/H/I/J/K',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm081',
  'numero': 81,
  'data': '2026-07-01',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo D',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo B/E/F/I/J',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'San Francisco Bay Area Stadium',
  'cidade': 'Santa Clara',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm082',
  'numero': 82,
  'data': '2026-07-01',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo G',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo A/E/H/I/J',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'Seattle Stadium',
  'cidade': 'Seattle',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm083',
  'numero': 83,
  'data': '2026-07-02',
  'hora': '20:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '2º Grupo K',
  'sigla_a': '2ºG',
  'pais_a': '',
  'time_b': '2º Grupo L',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Toronto Stadium',
  'cidade': 'Toronto',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm084',
  'numero': 84,
  'data': '2026-07-02',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo H',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '2º Grupo J',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm085',
  'numero': 85,
  'data': '2026-07-03',
  'hora': '00:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo B',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo E/F/G/I/J',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm086',
  'numero': 86,
  'data': '2026-07-03',
  'hora': '19:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo J',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '2º Grupo H',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm087',
  'numero': 87,
  'data': '2026-07-03',
  'hora': '22:30',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '1º Grupo K',
  'sigla_a': '1ºG',
  'pais_a': '',
  'time_b': '3º Grupo D/E/I/J/L',
  'sigla_b': '3ºG',
  'pais_b': '',
  'estadio': 'Kansas City Stadium',
  'cidade': 'Kansas City',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm088',
  'numero': 88,
  'data': '2026-07-03',
  'hora': '15:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '32 avos',
  'grupo': 'Mata-mata',
  'time_a': '2º Grupo D',
  'sigla_a': '2ºG',
  'pais_a': '',
  'time_b': '2º Grupo G',
  'sigla_b': '2ºG',
  'pais_b': '',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm089',
  'numero': 89,
  'data': '2026-07-04',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 74',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 77',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Philadelphia Stadium',
  'cidade': 'Filadélfia',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm090',
  'numero': 90,
  'data': '2026-07-04',
  'hora': '14:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 73',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 75',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Houston Stadium',
  'cidade': 'Houston',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm091',
  'numero': 91,
  'data': '2026-07-05',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 76',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 78',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm092',
  'numero': 92,
  'data': '2026-07-05',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 79',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 80',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Mexico City Stadium',
  'cidade': 'Cidade do México',
  'pais': 'México',
  'pais_sede': 'México',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm093',
  'numero': 93,
  'data': '2026-07-06',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 83',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 84',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm094',
  'numero': 94,
  'data': '2026-07-06',
  'hora': '21:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 81',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 82',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Seattle Stadium',
  'cidade': 'Seattle',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm095',
  'numero': 95,
  'data': '2026-07-07',
  'hora': '13:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 86',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 88',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm096',
  'numero': 96,
  'data': '2026-07-07',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Oitavas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 85',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 87',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Vancouver Stadium',
  'cidade': 'Vancouver',
  'pais': 'Canadá',
  'pais_sede': 'Canadá',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm097',
  'numero': 97,
  'data': '2026-07-09',
  'hora': '17:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Quartas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 89',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 90',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Boston Stadium',
  'cidade': 'Foxborough',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm098',
  'numero': 98,
  'data': '2026-07-10',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Quartas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 93',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 94',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Los Angeles Stadium',
  'cidade': 'Los Angeles',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm099',
  'numero': 99,
  'data': '2026-07-11',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Quartas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 91',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 92',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm100',
  'numero': 100,
  'data': '2026-07-11',
  'hora': '22:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Quartas',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 95',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 96',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Kansas City Stadium',
  'cidade': 'Kansas City',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm101',
  'numero': 101,
  'data': '2026-07-14',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Semifinal',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 97',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 98',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Dallas Stadium',
  'cidade': 'Arlington',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm102',
  'numero': 102,
  'data': '2026-07-15',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Semifinal',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 99',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 100',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'Atlanta Stadium',
  'cidade': 'Atlanta',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm103',
  'numero': 103,
  'data': '2026-07-18',
  'hora': '18:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': '3º lugar',
  'grupo': 'Mata-mata',
  'time_a': 'Perdedor Jogo 101',
  'sigla_a': 'PER',
  'pais_a': '',
  'time_b': 'Perdedor Jogo 102',
  'sigla_b': 'PER',
  'pais_b': '',
  'estadio': 'Miami Stadium',
  'cidade': 'Miami',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'},
 {'id': 'm104',
  'numero': 104,
  'data': '2026-07-19',
  'hora': '16:00',
  'timezone': 'America/Sao_Paulo',
  'horario_exibido': 'Brasília (UTC-03)',
  'fase': 'Final',
  'grupo': 'Mata-mata',
  'time_a': 'Vencedor Jogo 101',
  'sigla_a': 'VEN',
  'pais_a': '',
  'time_b': 'Vencedor Jogo 102',
  'sigla_b': 'VEN',
  'pais_b': '',
  'estadio': 'New York New Jersey Stadium',
  'cidade': 'Nova Jersey',
  'pais': 'EUA',
  'pais_sede': 'EUA',
  'status': 'agendado',
  'placar_a': None,
  'placar_b': None,
  'placar': '',
  'alerta': False,
  'favorito': False,
  'destaque': 'Confronto depende da classificação nas fases anteriores. Nomes exibidos como placeholders.',
  'fonte': 'FIFA / Sky Sports / resumo de agenda ChatGPT',
  'tipo_dado': 'oficial_com_placeholder'}]

STADIUM_INFO = {'Mexico City Stadium': {'capacidade': '87.000', 'inauguracao': '1966', 'gramado': 'Natural'},
 'Guadalajara Stadium': {'capacidade': '48.000', 'inauguracao': '2010', 'gramado': 'Natural'},
 'Monterrey Stadium': {'capacidade': '53.500', 'inauguracao': '2015', 'gramado': 'Natural'},
 'Toronto Stadium': {'capacidade': '45.000', 'inauguracao': '2007', 'gramado': 'Natural'},
 'Vancouver Stadium': {'capacidade': '54.500', 'inauguracao': '1983', 'gramado': 'Sintético/Natural temporário'},
 'Los Angeles Stadium': {'capacidade': '70.000', 'inauguracao': '2020', 'gramado': 'Natural temporário'},
 'San Francisco Bay Area Stadium': {'capacidade': '68.500', 'inauguracao': '2014', 'gramado': 'Natural'},
 'New York New Jersey Stadium': {'capacidade': '82.500', 'inauguracao': '2010', 'gramado': 'Natural temporário'},
 'Boston Stadium': {'capacidade': '65.000', 'inauguracao': '2002', 'gramado': 'Natural'},
 'Houston Stadium': {'capacidade': '72.000', 'inauguracao': '2002', 'gramado': 'Natural'},
 'Dallas Stadium': {'capacidade': '80.000', 'inauguracao': '2009', 'gramado': 'Natural temporário'},
 'Philadelphia Stadium': {'capacidade': '67.500', 'inauguracao': '2003', 'gramado': 'Natural'},
 'Atlanta Stadium': {'capacidade': '71.000', 'inauguracao': '2017', 'gramado': 'Natural temporário'},
 'Seattle Stadium': {'capacidade': '69.000', 'inauguracao': '2002', 'gramado': 'Natural temporário'},
 'Miami Stadium': {'capacidade': '65.000', 'inauguracao': '1987', 'gramado': 'Natural'},
 'Kansas City Stadium': {'capacidade': '76.000', 'inauguracao': '1972', 'gramado': 'Natural'}}

DEFAULT_PREFERENCES = {
    'tema': 'escuro',
    'cor_destaque': 'verde',
    'visual_compacto': False,
    'notificacoes': True,
    'alertas_jogos': True,
    'mudancas_horario': True,
    'favoritos_alerta': True,
    'fuso_horario': '(GMT-03:00) Brasília',
    'idioma': 'Português (Brasil)',
    'formato_data': 'DD/MM/AAAA',
}
